-- AlterTable
ALTER TABLE "Driver" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Tenant" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Vehicle" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
