version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lynx
      POSTGRES_USER: mathex
      POSTGRES_PASSWORD: Ma-241194
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: node:21
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - '4000:4000'
    depends_on:
      - db

volumes:
  db_data:
