### Criar um novo usuário
POST http://localhost:4000/users
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
  "email": "user@tenant5.com",
  "password": "password",
  "roleId": 2
}

### Login para obter o token JWT
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "admin@tenant1.com",
  "password": "password"
}

### Obter todos os usuários usando o token JWT
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODA0MDAwLCJleHAiOjE3MTk4MDc2MDB9.UewEn7xgQQFHWYV3IuYFVd2_mRpC-eZ-Mpc2huQHXoQ

### Logout usando o token JWT
POST http://localhost:4000/auth/logout
Authorization: Bearer YOUR_JWT_TOKEN_HERE

### Criar um novo motorista
POST http://localhost:4000/drivers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODA0MDAwLCJleHAiOjE3MTk4MDc2MDB9.UewEn7xgQQFHWYV3IuYFVd2_mRpC-eZ-Mpc2huQHXoQ

{
  "name": "Max Doe",
  "license": "ZBC123456",
  "cpf": "123.456.789-08"
}

### Obter todos os motoristas usando o token JWT
GET http://localhost:4000/drivers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODA0MDAwLCJleHAiOjE3MTk4MDc2MDB9.UewEn7xgQQFHWYV3IuYFVd2_mRpC-eZ-Mpc2huQHXoQ

### Criar um novo veículo
POST http://localhost:4000/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODA0MDAwLCJleHAiOjE3MTk4MDc2MDB9.UewEn7xgQQFHWYV3IuYFVd2_mRpC-eZ-Mpc2huQHXoQ

{
  "model": "Chevrolet Onix",
  "plate": "AYZ9876",
  "driverId": 4,
  "categoryId": 1
}

### Obter todas as categorias usando o token JWT
GET http://localhost:4000/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODA0MDAwLCJleHAiOjE3MTk4MDc2MDB9.UewEn7xgQQFHWYV3IuYFVd2_mRpC-eZ-Mpc2huQHXoQ


### Obter todos os veículos usando o token JWT
GET http://localhost:4000/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODA0MDAwLCJleHAiOjE3MTk4MDc2MDB9.UewEn7xgQQFHWYV3IuYFVd2_mRpC-eZ-Mpc2huQHXoQ

### Criar uma nova direção
POST http://localhost:4000/directions
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
  "rangeInicio": "01000000",
  "rangeFim": "01259999",
  "valorDirecao": "1",
  "regiao": "Zona Central"
}

### Obter todas as direções usando o token JWT
GET http://localhost:4000/directions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAdGVuYW50Mi5jb20iLCJzdWIiOjQsInJvbGUiOiJ1c2VyIiwidGVuYW50SWQiOjIsImlhdCI6MTcxOTgwMDc0NCwiZXhwIjoxNzE5ODA0MzQ0fQ.iulWvmGha48dIJSqcd07KOlx3ILUZb9jCI2oZmVKxD0

### Obter uma direção por ID usando o token JWT
GET http://localhost:4000/directions/1
Authorization: Bearer YOUR_JWT_TOKEN_HERE

### Atualizar uma direção
PATCH http://localhost:4000/directions/1
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
  "valorDirecao": "2"
}

### Remover uma direção
DELETE http://localhost:4000/directions/1
Authorization: Bearer YOUR_JWT_TOKEN_HERE

### Obter todos os pedidos usando o token JWT
GET http://localhost:4000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODUyMDQ1LCJleHAiOjE3MTk4NTU2NDV9.d_mcQ4NkTt4Zp370AvEa-3LgVjyAugyM43KMChx_OHw

### Obter todos os roteiros usando o token JWT
GET http://localhost:4000/delivery
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAdGVuYW50Mi5jb20iLCJzdWIiOjQsInJvbGUiOiJ1c2VyIiwidGVuYW50SWQiOjIsImlhdCI6MTcxOTgwMDc0NCwiZXhwIjoxNzE5ODA0MzQ0fQ.iulWvmGha48dIJSqcd07KOlx3ILUZb9jCI2oZmVKxD0

### Criar um novo delivery
POST http://localhost:4000/delivery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODQyNzI1LCJleHAiOjE3MTk4NDYzMjV9.6HGk55Igj4lE-czYYAlCUdqTr5WzIWvE9svd4TfxP-o

{
  "motoristaId": 1, 
  "veiculoId": 1,
  "orders": [1,2]
}

### Obter os delivery
GET  http://localhost:4000/delivery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODUyMDQ1LCJleHAiOjE3MTk4NTU2NDV9.d_mcQ4NkTt4Zp370AvEa-3LgVjyAugyM43KMChx_OHw

### Obter os delivery
PATCH  http://localhost:4000/delivery/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODUyMDQ1LCJleHAiOjE3MTk4NTU2NDV9.d_mcQ4NkTt4Zp370AvEa-3LgVjyAugyM43KMChx_OHw

{
  "status": "Finalizado", 
  "dataFim": "2024-08-01T14:09:29.913Z"
}

### Obter categorias
GET  http://localhost:4000/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODUyMDQ1LCJleHAiOjE3MTk4NTU2NDV9.d_mcQ4NkTt4Zp370AvEa-3LgVjyAugyM43KMChx_OHw

### Obter payments
GET  http://localhost:4000/payments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODUyMDQ1LCJleHAiOjE3MTk4NTU2NDV9.d_mcQ4NkTt4Zp370AvEa-3LgVjyAugyM43KMChx_OHw

### Criar um novo payment
POST http://localhost:4000/delivery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlbmFudDEuY29tIiwic3ViIjoxLCJyb2xlIjoiYWRtaW4iLCJ0ZW5hbnRJZCI6MSwiaWF0IjoxNzE5ODQyNzI1LCJleHAiOjE3MTk4NDYzMjV9.6HGk55Igj4lE-czYYAlCUdqTr5WzIWvE9svd4TfxP-o

{
  "motoristaId": 1, 
  "veiculoId": 1,
  "orders": [1,2]
}
